w5/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [ 
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logout, name="logout"),
    path('admin/', views.admin, name="admin"),
    path('delete/<int:pk>/', views.DeleteUserView.as_view(), name='delete'),
    path('', views.welcome, name="welcome"),
]

w5/contacts/urls.py
from django.urls import path
from . import views

app_name="contacts"
urlpatterns = [ 
    path('create/', views.add_contact, name="create"),
]

w5/w5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
]

w5/w6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('stores/', include('stores.urls', namespace='stores')),
    path('admin/', admin.site.urls),
] + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

w5/accounts/models.py
from django.db import models

# Create your models here.

w5/contacts/models.py
from django.contrib.auth.models import User
from django.db import models

class AddressBook(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.name}"

class ContactGroup(models.Model):
    name = models.CharField(max_length=255)
    book = models.ForeignKey(AddressBook, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, 
                               null=True, blank=True)

class Contact(models.Model):
    name = models.CharField(max_length=255)
    fax = models.CharField(max_length=32)
    email = models.EmailField()
    method = models.CharField(max_length=32, blank=True)
    book = models.ForeignKey(AddressBook, on_delete=models.CASCADE)
    groups = models.ManyToManyField(ContactGroup, blank=True)

w5/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        data = super().clean()
        user = authenticate(username=data.get('username'), password=data.get('password'))
        if not user:
            raise ValidationError({
                'username' : 'Invalid username and password combination'}
            )
        data['user'] = user
        return data

class SignupForm(UserCreationForm):   
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        error_messages = {
            'email' : {
                'invalid' : "Your email address makes no sense.",
            }
        }

w5/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as login_user, \
                                logout as logout_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import FormView, CreateView, DeleteView
from django.views.generic.list import ListView
from .forms import LoginForm, SignupForm

class LoginView(FormView):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('accounts:admin')
    def form_valid(self, form):
        login_user(self.request, form.cleaned_data['user'])
        return super().form_valid(form)

def logout(request):
    logout_user(request)
    request.session['from'] = 'logout'
    return redirect(reverse('accounts:welcome'))

class SignupView(CreateView):
    form_class = SignupForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('accounts:welcome')
    
    # note that ModelForm saves object automatically
    def form_valid(self, form):
        self.request.session['from'] = 'signup' 
        return super().form_valid(form)

@login_required(login_url=reverse_lazy('accounts:login'))
def admin(request):
    keyword = request.GET.get('filter', '')
    return render(request, "accounts/admin.html", {
        'user_list' : User.objects.filter(username__icontains=keyword),
    })

class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = User
    login_url = reverse_lazy('accounts:login')
    success_url = reverse_lazy('accounts:admin')

def welcome(request):
    from_view = request.session.pop('from', '')
    if request.user.is_authenticated:
        return redirect(reverse('accounts:admin'))
    return render(request, "accounts/welcome.html", {
        'from' : from_view,
    })

w5/contacts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotAllowed
from django.forms import ModelForm
from .models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        exclude = [ 'groups', ]
        labels = {
            'book' : "Address Book",
        }

def user_owns_address_book(request, form):
    return request.user == form.cleaned_data['book'].user

# this assumes user and address book already exists
def add_contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid() and user_owns_address_book(request, form):
            form.save()
            return redirect("contacts:create")
    elif request.method == "GET":
        form = ContactForm()
    else:
        return HttpResponseNotAllowed()
    return render(request, "contacts/create.html", {
        "form" : form,
    })

w5/accounts/templates/accounts/admin.html
{% extends './base.html' %}
{% block title %}Account Administration{% endblock %}
{% block content %}
<h1>User Administration</h1>
<form class="flex-form" method="GET">
  <input type="text" id="filter" name="filter"
          value="{{ request.GET.filter }}">
  <button type="submit">Filter</button>
</form>
{% if request.GET.filter %}
<p>User name that contains: <b>{{ request.GET.filter }}</b></p>
{% endif %}
{% if user_list|length > 0 %}
<table>
  <tr>
    <th>User Name</th><th>Email</th><th>Date Joined</th><th>Action</th>
  </tr>
  {% for user in user_list %}
  <tr>
    <td>{{ user.username }}</td>
    <td>{{ user.email }}</td>
    <td>{{ user.date_joined | date:'Y-m-d H:i' }}</td>
    <td>
    {% if not user.is_staff and user != request.user %}
    <form method="POST" action="{% url 'accounts:delete' user.pk %}">
      {% csrf_token %}
      <button class="danger" type="submit">Delete</button>
    </form>
    {% endif %}
    </td>
  </tr>
  {% endfor %}
</table>
{% else %}
<h3>Your filter result returned nothing.</h3>
{% endif %}
<p>
  Click <a href="{% url 'accounts:logout' %}">here to logout</a>.
</p>
{% endblock %}

w5/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"> 
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Accounts Page{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
  <main>
    {% block content %}{% endblock %}
  </main>
</body>
</html>

w5/accounts/templates/accounts/form.html
{% for field in form %}
{{ field.label_tag }}{{ field }}
{% if field.errors %}
{% for error in field.errors %}
<label>{# empty label for grid column #}</label>
<p class="error">{{ error }}</p>
{% endfor %}
{% endif %}
{% endfor %}

w5/accounts/templates/accounts/login.html
{% extends "./base.html" %}
{% block title %}Signup{% endblock %}
{% block content %}
<h2>Please enter your login information</h2>
<form class="container" action="{% url 'accounts:login' %}" 
      method="POST">
{% csrf_token %}      
    
{% include './form.html' %}
<button type="submit">Login</button>
</form>
<p><a href="{% url 'accounts:signup' %}">Need an account?</a></p>
{% endblock %}

w5/accounts/templates/accounts/signup.html
{% extends './base.html' %}
{% block title %}Account Signup{% endblock %}
{% block content %}
<h2>Please enter your information</h2>
<form class="container" action="{% url 'accounts:signup' %}" 
      method="POST">
{% csrf_token %}      
{% include './form.html' %}
<button type="submit">Sign me up!</button>
</form>
{% endblock %}

w5/accounts/templates/accounts/welcome.html
{% extends './base.html' %}

{% block title %}Welcome Page{% endblock %}

{% block content %}
<h1>Welcome!</h1>
<p>
  {% if from == "signup" %}
  Account registration was successful.
  {% elif from == "logout" %}
  You have been successfully logged out.
  {% else %}
  Welcome to the account management page.
  {% endif %}
  Click <a href="{% url 'accounts:login' %}">here to login</a>
  or <a href="{% url 'accounts:signup' %}">here to signup</a>.
</p>
{% endblock %}

w5/contacts/templates/contacts/create.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"> 
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create Contact</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
  <main>
    <h1>Create Contact</h1>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </main>
</body>
</html>